"""empty message

Revision ID: 696cd50e264f
Revises: 9c69864cff6b
Create Date: 2020-09-09 15:27:40.847782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696cd50e264f'
down_revision = '9c69864cff6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gramsFlour', sa.Float(), nullable=True),
    sa.Column('gramsWater', sa.Float(), nullable=True),
    sa.Column('gramsStarter', sa.Float(), nullable=True),
    sa.Column('numStretchFold', sa.Integer(), nullable=True),
    sa.Column('autolyseTime', sa.Float(), nullable=True),
    sa.Column('bulkFermentTime', sa.Float(), nullable=True),
    sa.Column('bakeTime', sa.Float(), nullable=True),
    sa.Column('overallQuality', sa.Integer(), nullable=True),
    sa.Column('rise', sa.Integer(), nullable=True),
    sa.Column('crumb', sa.Integer(), nullable=True),
    sa.Column('ear', sa.Integer(), nullable=True),
    sa.Column('flavor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('carsTest3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carsTest3',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"carsTest3_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('doors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='carsTest3_pkey')
    )
    op.drop_table('bakes')
    # ### end Alembic commands ###
