"""empty message

Revision ID: 83b6f339fdd4
Revises: 696cd50e264f
Create Date: 2020-09-09 16:46:05.183280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b6f339fdd4'
down_revision = '696cd50e264f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bakes', sa.Column('crust', sa.Integer(), nullable=True))
    op.drop_column('bakes', 'ear')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bakes', sa.Column('ear', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('bakes', 'crust')
    # ### end Alembic commands ###
